FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Production 

COPY *.csproj ./
RUN dotnet restore
# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out
# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime
WORKDIR /app

FROM mcr.microsoft.com/dotnet/runtime:3.1
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "DBApp.dll"]